# Generated by Django 4.2.11 on 2024-03-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='datetime',
            field=models.DateTimeField(verbose_name='Date and Time'),
        ),
    ]
