# Generated by Django 4.2.11 on 2024-03-19 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_club_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='agenda',
        ),
        migrations.RemoveField(
            model_name='club',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='club',
            name='venue',
        ),
    ]
